security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            
            oauth:
                failure_path: /login/connect             
                login_path: /login/connect             
                check_path: /login/connect
                provider: fos_userbundle
                resource_owners:
                    google:       "/login/login/check-google"
                oauth_user_provider:
                    service: my_user_provider
            anonymous:    true
            logout:
                path:           /login/logout
                target:         /
            
            
        login:
            pattern:  ^/login$
            security: false
 
            remember_me:
                key: "%secret%"
                lifetime: 31536000
                path: /
                domain: ~
    access_control:
            - { path: ^/login/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/login/connect, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/login, role: ROLE_USER }
