<?php

namespace NZ\PlatformBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * IngredientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IngredientRepository extends EntityRepository
{
	public function getIngredientWithKeyword($keyword)
	  {
	    $qb = $this->createQueryBuilder('a');
	
	    $qb
	      ->where('a.name LIKE :keyword')
	      ->setParameter('keyword','%'.$keyword.'%')
	      ->orderBy('a.name','ASC')
	    ;

	    return $qb->getQuery()->getResult()
	    ;
	  }
}
